<a href="https://colab.research.google.com/github/anisaardn/Needleman-Wunsch-Algorithm/blob/main/NEEDLEMAN_WUNSCH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing Modules
import numpy as np

In [2]:
# Ask for sequences from the user
sequence_1 = input("Enter the first sequence: ")
sequence_2 = input("Enter the second sequence: ")

Enter the first sequence: ATCGT
Enter the second sequence: ACGT


In [7]:
# Create Matrices
main_matrix = np.zeros((len(sequence_1)+1,len(sequence_2)+1))
match_checker_matrix = np.zeros((len(sequence_1),len(sequence_2)))

In [8]:
# Providing the scores for match, mismatch, and gap
match_reward = 1
mismatch_penalty = -1
gap_penalty = -2

In [9]:
# Fill the match checker matrix according to match or mismatch
for i in range(len(sequence_1)):
  for j in range(len(sequence_2)):
    if sequence_1[i] == sequence_2[j]:
      match_checker_matrix[i][j] = match_reward
    else:
      match_checker_matrix[i][j] = mismatch_penalty

In [10]:
print(match_checker_matrix)

[[ 1. -1. -1. -1.]
 [-1. -1. -1.  1.]
 [-1.  1. -1. -1.]
 [-1. -1.  1. -1.]
 [-1. -1. -1.  1.]]


In [11]:
# Filling up the matrix using Needleman-Wunsch
# STEP 1: INITIALIZATION
for i in range(len(sequence_1)+1):
  main_matrix[i][0] = gap_penalty*i
for j in range(len(sequence_2)+1):
  main_matrix[0][j] = gap_penalty*j

In [12]:
# STEP 2: MATRIX FILLING
for i in range(1,len(sequence_1)+1):
  for j in range(1,len(sequence_2)+1):
    main_matrix[i][j] = max(main_matrix[i-1][j-1]+match_checker_matrix[i-1][j-1],
                            main_matrix[i-1][j]+gap_penalty,
                            main_matrix[i][j-1]+gap_penalty)

In [13]:
# STEP 3: TRACEBACK
aligned_1 = ""
aligned_2 = ""

ti = len(sequence_1)
tj = len(sequence_2)

while(ti >0 and tj > 0):
  if (ti > 0 and tj > 0 and main_matrix[ti][tj]== main_matrix[ti-1][tj-1]+ match_checker_matrix[ti-1][tj-1]):
    aligned_1 = sequence_1[ti-1] + aligned_1
    aligned_2 = sequence_2[tj-1] + aligned_2
    ti = ti-1
    tj = tj-1
  elif(ti > 0 and main_matrix[ti][tj]== main_matrix[ti-1][tj]+gap_penalty):
    aligned_1 = sequence_1[ti-1] + aligned_1
    aligned_2 = "-" + aligned_2
    ti = ti-1
  else:
    aligned_1 = "-" + aligned_1
    aligned_2 = sequence_2[tj-1] + aligned_2
    tj = tj-1


In [14]:
# TEST
print(aligned_1)
print(aligned_2)

ATCGT
A-CGT
