<a href="https://colab.research.google.com/github/anisaardn/Needleman-Wunsch-Algorithm/blob/main/NEEDLEMAN_WUNSCH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
# Importing Modules
import numpy as np

In [25]:
# Ask for sequences from the user
# sequence_1 = input("Enter the first sequence: ")
# sequence_2 = input("Enter the second sequence: ")

In [26]:
# Ask for sequences from the user
sequence_1 = "AGCATGCG"
sequence_2 = "ATGCAAG"

In [27]:
# Create Matrices
main_matrix = np.zeros((len(sequence_1)+1,len(sequence_2)+1))
match_checker_matrix = np.zeros((len(sequence_1),len(sequence_2)))

In [28]:
# Providing the scores for match, mismatch, and gap
match_reward = 1
mismatch_penalty = -1
gap_penalty = -2

In [29]:
# Fill the match checker matrix according to match or mismatch
for i in range(len(sequence_1)):
  for j in range(len(sequence_2)):
    if sequence_1[i] == sequence_2[j]:
      match_checker_matrix[i][j] = match_reward
    else:
      match_checker_matrix[i][j] = mismatch_penalty

In [30]:
print(match_checker_matrix)

[[ 1. -1. -1. -1.  1.  1. -1.]
 [-1. -1.  1. -1. -1. -1.  1.]
 [-1. -1. -1.  1. -1. -1. -1.]
 [ 1. -1. -1. -1.  1.  1. -1.]
 [-1.  1. -1. -1. -1. -1. -1.]
 [-1. -1.  1. -1. -1. -1.  1.]
 [-1. -1. -1.  1. -1. -1. -1.]
 [-1. -1.  1. -1. -1. -1.  1.]]


In [31]:
# Filling up the matrix using Needleman-Wunsch
# STEP 1: INITIALIZATION
for i in range(len(sequence_1)+1):
  main_matrix[i][0] = gap_penalty*i
for j in range(len(sequence_2)+1):
  main_matrix[0][j] = gap_penalty*j

In [32]:
# STEP 2: MATRIX FILLING
for i in range(1,len(sequence_1)+1):
  for j in range(1,len(sequence_2)+1):
    main_matrix[i][j] = max(main_matrix[i-1][j-1]+match_checker_matrix[i-1][j-1],
                            main_matrix[i-1][j]+gap_penalty,
                            main_matrix[i][j-1]+gap_penalty)

In [33]:
# STEP 3: TRACEBACK
aligned_1 = ""
aligned_2 = ""

ti = len(sequence_1)
tj = len(sequence_2)

while(ti >0 and tj > 0):
  if (ti > 0 and tj > 0 and main_matrix[ti][tj]== main_matrix[ti-1][tj-1]+ match_checker_matrix[ti-1][tj-1]):
    aligned_1 = sequence_1[ti-1] + aligned_1
    aligned_2 = sequence_2[tj-1] + aligned_2
    ti = ti-1
    tj = tj-1
  elif(ti > 0 and main_matrix[ti][tj]== main_matrix[ti-1][tj]+gap_penalty):
    aligned_1 = sequence_1[ti-1] + aligned_1
    aligned_2 = "-" + aligned_2
    ti = ti-1
  else:
    aligned_1 = "-" + aligned_1
    aligned_2 = sequence_2[tj-1] + aligned_2
    tj = tj-1


In [34]:
# TEST
print(aligned_1)
print(aligned_2)

A-GCATGCG
ATGCA--AG


In [35]:
# Print Score
alignment_score = main_matrix[len(sequence_1)][len(sequence_2)]
print("Alignment Score:", alignment_score)

Alignment Score: -2.0


In [36]:
print("Main Matrix (Scoring Matrix):")
print(main_matrix)

Main Matrix (Scoring Matrix):
[[  0.  -2.  -4.  -6.  -8. -10. -12. -14.]
 [ -2.   1.  -1.  -3.  -5.  -7.  -9. -11.]
 [ -4.  -1.   0.   0.  -2.  -4.  -6.  -8.]
 [ -6.  -3.  -2.  -1.   1.  -1.  -3.  -5.]
 [ -8.  -5.  -4.  -3.  -1.   2.   0.  -2.]
 [-10.  -7.  -4.  -5.  -3.   0.   1.  -1.]
 [-12.  -9.  -6.  -3.  -5.  -2.  -1.   2.]
 [-14. -11.  -8.  -5.  -2.  -4.  -3.   0.]
 [-16. -13. -10.  -7.  -4.  -3.  -5.  -2.]]


In [37]:
# Alignment score
alignment_score = main_matrix[len(sequence_1)][len(sequence_2)]
print("Alignment Score:", alignment_score)

# TEST
print("Aligned Sequence 1:", aligned_1)
print("Aligned Sequence 2:", aligned_2)

Alignment Score: -2.0
Aligned Sequence 1: A-GCATGCG
Aligned Sequence 2: ATGCA--AG


In [39]:
def score_alignment(al1, al2, match=1, mismatch=-1, gap=-2):
    assert len(al1) == len(al2), "Panjang kedua alignment harus sama"
    score = 0
    for a, b in zip(al1, al2):
        if a == '-' or b == '-':
            score += gap
        elif a == b:
            score += match
        else:
            score += mismatch
    return score

# Contoh penggunaan:
seq1 = "A-TCAAGCG"
seq2 = "ATGCA--AG"

print("Score:", score_alignment(seq1, seq2))

Score: -4
